[theme]
name = "Tango"

[theme.colors]
foreground = "#EEEEEC"
background = "#2E3436"
cursor = "#EEEEEC"
selection_fg = "#2E3436"
selection_bg = "#D3D7CF"

[theme.colors.ansi]
black          = "#2E3436"
red            = "#CC0000"
green          = "#4E9A06"
yellow         = "#C4A000"
blue           = "#3465A4"
magenta        = "#75507B"
cyan           = "#06989A"
white          = "#D3D7CF"
bright_black   = "#555753"
bright_red     = "#EF2929"
bright_green   = "#8AE234"
bright_yellow  = "#FCE94F"
bright_blue    = "#729FCF"
bright_magenta = "#AD7FA8"
bright_cyan    = "#34E2E2"
bright_white   = "#EEEEEC"

[theme.ui]
scrollbar_bg = "#2E3436"
scrollbar_thumb = "#555753"
scrollbar_thumb_hover = "#888A85"
