// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package handoff

import (
	"github.com/LXXero/xerotty/internal/protocol"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *State) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "version":
			z.Version, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "instance_id":
			z.InstanceID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "InstanceID")
				return
			}
		case "next_tab_id":
			z.NextTabID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "NextTabID")
				return
			}
		case "next_window_id":
			z.NextWindowID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "NextWindowID")
				return
			}
		case "revision":
			z.Revision, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Revision")
				return
			}
		case "windows":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Windows")
				return
			}
			if cap(z.Windows) >= int(zb0002) {
				z.Windows = (z.Windows)[:zb0002]
			} else {
				z.Windows = make([]protocol.WindowInfo, zb0002)
			}
			for za0001 := range z.Windows {
				err = z.Windows[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Windows", za0001)
					return
				}
			}
		case "tabs":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Tabs")
				return
			}
			if cap(z.Tabs) >= int(zb0003) {
				z.Tabs = (z.Tabs)[:zb0003]
			} else {
				z.Tabs = make([]TabState, zb0003)
			}
			for za0002 := range z.Tabs {
				err = z.Tabs[za0002].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Tabs", za0002)
					return
				}
			}
		case "wire_listen_fd":
			z.WireListenFD, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "WireListenFD")
				return
			}
		case "mcp_listen_fd":
			z.MCPListenFD, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "MCPListenFD")
				return
			}
		case "socket_path":
			z.SocketPath, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SocketPath")
				return
			}
		case "mcp_socket":
			z.MCPSocket, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "MCPSocket")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *State) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 11
	// write "version"
	err = en.Append(0x8b, 0xa7, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Version)
	if err != nil {
		err = msgp.WrapError(err, "Version")
		return
	}
	// write "instance_id"
	err = en.Append(0xab, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.InstanceID)
	if err != nil {
		err = msgp.WrapError(err, "InstanceID")
		return
	}
	// write "next_tab_id"
	err = en.Append(0xab, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x74, 0x61, 0x62, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.NextTabID)
	if err != nil {
		err = msgp.WrapError(err, "NextTabID")
		return
	}
	// write "next_window_id"
	err = en.Append(0xae, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.NextWindowID)
	if err != nil {
		err = msgp.WrapError(err, "NextWindowID")
		return
	}
	// write "revision"
	err = en.Append(0xa8, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Revision)
	if err != nil {
		err = msgp.WrapError(err, "Revision")
		return
	}
	// write "windows"
	err = en.Append(0xa7, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Windows)))
	if err != nil {
		err = msgp.WrapError(err, "Windows")
		return
	}
	for za0001 := range z.Windows {
		err = z.Windows[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Windows", za0001)
			return
		}
	}
	// write "tabs"
	err = en.Append(0xa4, 0x74, 0x61, 0x62, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Tabs)))
	if err != nil {
		err = msgp.WrapError(err, "Tabs")
		return
	}
	for za0002 := range z.Tabs {
		err = z.Tabs[za0002].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Tabs", za0002)
			return
		}
	}
	// write "wire_listen_fd"
	err = en.Append(0xae, 0x77, 0x69, 0x72, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x66, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt(z.WireListenFD)
	if err != nil {
		err = msgp.WrapError(err, "WireListenFD")
		return
	}
	// write "mcp_listen_fd"
	err = en.Append(0xad, 0x6d, 0x63, 0x70, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x66, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt(z.MCPListenFD)
	if err != nil {
		err = msgp.WrapError(err, "MCPListenFD")
		return
	}
	// write "socket_path"
	err = en.Append(0xab, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.SocketPath)
	if err != nil {
		err = msgp.WrapError(err, "SocketPath")
		return
	}
	// write "mcp_socket"
	err = en.Append(0xaa, 0x6d, 0x63, 0x70, 0x5f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.MCPSocket)
	if err != nil {
		err = msgp.WrapError(err, "MCPSocket")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *State) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 11
	// string "version"
	o = append(o, 0x8b, 0xa7, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendUint16(o, z.Version)
	// string "instance_id"
	o = append(o, 0xab, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.InstanceID)
	// string "next_tab_id"
	o = append(o, 0xab, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x74, 0x61, 0x62, 0x5f, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.NextTabID)
	// string "next_window_id"
	o = append(o, 0xae, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.NextWindowID)
	// string "revision"
	o = append(o, 0xa8, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendUint64(o, z.Revision)
	// string "windows"
	o = append(o, 0xa7, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Windows)))
	for za0001 := range z.Windows {
		o, err = z.Windows[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Windows", za0001)
			return
		}
	}
	// string "tabs"
	o = append(o, 0xa4, 0x74, 0x61, 0x62, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Tabs)))
	for za0002 := range z.Tabs {
		o, err = z.Tabs[za0002].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Tabs", za0002)
			return
		}
	}
	// string "wire_listen_fd"
	o = append(o, 0xae, 0x77, 0x69, 0x72, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x66, 0x64)
	o = msgp.AppendInt(o, z.WireListenFD)
	// string "mcp_listen_fd"
	o = append(o, 0xad, 0x6d, 0x63, 0x70, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x66, 0x64)
	o = msgp.AppendInt(o, z.MCPListenFD)
	// string "socket_path"
	o = append(o, 0xab, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68)
	o = msgp.AppendString(o, z.SocketPath)
	// string "mcp_socket"
	o = append(o, 0xaa, 0x6d, 0x63, 0x70, 0x5f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74)
	o = msgp.AppendString(o, z.MCPSocket)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *State) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "version":
			z.Version, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "instance_id":
			z.InstanceID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "InstanceID")
				return
			}
		case "next_tab_id":
			z.NextTabID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NextTabID")
				return
			}
		case "next_window_id":
			z.NextWindowID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NextWindowID")
				return
			}
		case "revision":
			z.Revision, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Revision")
				return
			}
		case "windows":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Windows")
				return
			}
			if cap(z.Windows) >= int(zb0002) {
				z.Windows = (z.Windows)[:zb0002]
			} else {
				z.Windows = make([]protocol.WindowInfo, zb0002)
			}
			for za0001 := range z.Windows {
				bts, err = z.Windows[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Windows", za0001)
					return
				}
			}
		case "tabs":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Tabs")
				return
			}
			if cap(z.Tabs) >= int(zb0003) {
				z.Tabs = (z.Tabs)[:zb0003]
			} else {
				z.Tabs = make([]TabState, zb0003)
			}
			for za0002 := range z.Tabs {
				bts, err = z.Tabs[za0002].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Tabs", za0002)
					return
				}
			}
		case "wire_listen_fd":
			z.WireListenFD, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "WireListenFD")
				return
			}
		case "mcp_listen_fd":
			z.MCPListenFD, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MCPListenFD")
				return
			}
		case "socket_path":
			z.SocketPath, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SocketPath")
				return
			}
		case "mcp_socket":
			z.MCPSocket, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MCPSocket")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *State) Msgsize() (s int) {
	s = 1 + 8 + msgp.Uint16Size + 12 + msgp.StringPrefixSize + len(z.InstanceID) + 12 + msgp.Uint32Size + 15 + msgp.Uint32Size + 9 + msgp.Uint64Size + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Windows {
		s += z.Windows[za0001].Msgsize()
	}
	s += 5 + msgp.ArrayHeaderSize
	for za0002 := range z.Tabs {
		s += z.Tabs[za0002].Msgsize()
	}
	s += 15 + msgp.IntSize + 14 + msgp.IntSize + 12 + msgp.StringPrefixSize + len(z.SocketPath) + 11 + msgp.StringPrefixSize + len(z.MCPSocket)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TabState) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "title":
			z.Title, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "cwd":
			z.CWD, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "CWD")
				return
			}
		case "cols":
			z.Cols, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Cols")
				return
			}
		case "rows":
			z.Rows, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Rows")
				return
			}
		case "ptmx_fd":
			z.PtmxFD, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "PtmxFD")
				return
			}
		case "child_pid":
			z.ChildPID, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "ChildPID")
				return
			}
		case "exited":
			z.Exited, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Exited")
				return
			}
		case "exit_code":
			z.ExitCode, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "ExitCode")
				return
			}
		case "last_output_at":
			z.LastOutputAt, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "LastOutputAt")
				return
			}
		case "last_input_at":
			z.LastInputAt, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "LastInputAt")
				return
			}
		case "screen":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Screen")
				return
			}
			if cap(z.Screen) >= int(zb0002) {
				z.Screen = (z.Screen)[:zb0002]
			} else {
				z.Screen = make([][]protocol.Cell, zb0002)
			}
			for za0001 := range z.Screen {
				var zb0003 uint32
				zb0003, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "Screen", za0001)
					return
				}
				if cap(z.Screen[za0001]) >= int(zb0003) {
					z.Screen[za0001] = (z.Screen[za0001])[:zb0003]
				} else {
					z.Screen[za0001] = make([]protocol.Cell, zb0003)
				}
				for za0002 := range z.Screen[za0001] {
					err = z.Screen[za0001][za0002].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Screen", za0001, za0002)
						return
					}
				}
			}
		case "cursor_row":
			z.CursorRow, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "CursorRow")
				return
			}
		case "cursor_col":
			z.CursorCol, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "CursorCol")
				return
			}
		case "cursor_style":
			z.CursorStyle, err = dc.ReadUint8()
			if err != nil {
				err = msgp.WrapError(err, "CursorStyle")
				return
			}
		case "cursor_blink":
			z.CursorBlink, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "CursorBlink")
				return
			}
		case "style_set":
			z.StyleSet, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "StyleSet")
				return
			}
		case "app_cursor":
			z.AppCursor, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "AppCursor")
				return
			}
		case "mem_scrollback":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "MemScrollback")
				return
			}
			if cap(z.MemScrollback) >= int(zb0004) {
				z.MemScrollback = (z.MemScrollback)[:zb0004]
			} else {
				z.MemScrollback = make([][]protocol.Cell, zb0004)
			}
			for za0003 := range z.MemScrollback {
				var zb0005 uint32
				zb0005, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "MemScrollback", za0003)
					return
				}
				if cap(z.MemScrollback[za0003]) >= int(zb0005) {
					z.MemScrollback[za0003] = (z.MemScrollback[za0003])[:zb0005]
				} else {
					z.MemScrollback[za0003] = make([]protocol.Cell, zb0005)
				}
				for za0004 := range z.MemScrollback[za0003] {
					err = z.MemScrollback[za0003][za0004].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "MemScrollback", za0003, za0004)
						return
					}
				}
			}
		case "disk_fd":
			z.DiskFD, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "DiskFD")
				return
			}
		case "disk_offsets":
			var zb0006 uint32
			zb0006, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "DiskOffsets")
				return
			}
			if cap(z.DiskOffsets) >= int(zb0006) {
				z.DiskOffsets = (z.DiskOffsets)[:zb0006]
			} else {
				z.DiskOffsets = make([]int64, zb0006)
			}
			for za0005 := range z.DiskOffsets {
				z.DiskOffsets[za0005], err = dc.ReadInt64()
				if err != nil {
					err = msgp.WrapError(err, "DiskOffsets", za0005)
					return
				}
			}
		case "disk_size":
			z.DiskSize, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "DiskSize")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TabState) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(23)
	var zb0001Mask uint32 /* 23 bits */
	_ = zb0001Mask
	if z.Name == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Title == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.CWD == "" {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Exited == false {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.ExitCode == 0 {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.LastOutputAt == 0 {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.LastInputAt == 0 {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	if z.CursorStyle == 0 {
		zb0001Len--
		zb0001Mask |= 0x8000
	}
	if z.CursorBlink == false {
		zb0001Len--
		zb0001Mask |= 0x10000
	}
	if z.StyleSet == false {
		zb0001Len--
		zb0001Mask |= 0x20000
	}
	if z.AppCursor == false {
		zb0001Len--
		zb0001Mask |= 0x40000
	}
	if z.MemScrollback == nil {
		zb0001Len--
		zb0001Mask |= 0x80000
	}
	if z.DiskOffsets == nil {
		zb0001Len--
		zb0001Mask |= 0x200000
	}
	if z.DiskSize == 0 {
		zb0001Len--
		zb0001Mask |= 0x400000
	}
	// variable map header, size zb0001Len
	err = en.WriteMapHeader(zb0001Len)
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "id"
		err = en.Append(0xa2, 0x69, 0x64)
		if err != nil {
			return
		}
		err = en.WriteUint32(z.ID)
		if err != nil {
			err = msgp.WrapError(err, "ID")
			return
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "name"
			err = en.Append(0xa4, 0x6e, 0x61, 0x6d, 0x65)
			if err != nil {
				return
			}
			err = en.WriteString(z.Name)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "title"
			err = en.Append(0xa5, 0x74, 0x69, 0x74, 0x6c, 0x65)
			if err != nil {
				return
			}
			err = en.WriteString(z.Title)
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "cwd"
			err = en.Append(0xa3, 0x63, 0x77, 0x64)
			if err != nil {
				return
			}
			err = en.WriteString(z.CWD)
			if err != nil {
				err = msgp.WrapError(err, "CWD")
				return
			}
		}
		// write "cols"
		err = en.Append(0xa4, 0x63, 0x6f, 0x6c, 0x73)
		if err != nil {
			return
		}
		err = en.WriteInt(z.Cols)
		if err != nil {
			err = msgp.WrapError(err, "Cols")
			return
		}
		// write "rows"
		err = en.Append(0xa4, 0x72, 0x6f, 0x77, 0x73)
		if err != nil {
			return
		}
		err = en.WriteInt(z.Rows)
		if err != nil {
			err = msgp.WrapError(err, "Rows")
			return
		}
		// write "ptmx_fd"
		err = en.Append(0xa7, 0x70, 0x74, 0x6d, 0x78, 0x5f, 0x66, 0x64)
		if err != nil {
			return
		}
		err = en.WriteInt(z.PtmxFD)
		if err != nil {
			err = msgp.WrapError(err, "PtmxFD")
			return
		}
		// write "child_pid"
		err = en.Append(0xa9, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x5f, 0x70, 0x69, 0x64)
		if err != nil {
			return
		}
		err = en.WriteInt(z.ChildPID)
		if err != nil {
			err = msgp.WrapError(err, "ChildPID")
			return
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// write "exited"
			err = en.Append(0xa6, 0x65, 0x78, 0x69, 0x74, 0x65, 0x64)
			if err != nil {
				return
			}
			err = en.WriteBool(z.Exited)
			if err != nil {
				err = msgp.WrapError(err, "Exited")
				return
			}
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// write "exit_code"
			err = en.Append(0xa9, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65)
			if err != nil {
				return
			}
			err = en.WriteInt(z.ExitCode)
			if err != nil {
				err = msgp.WrapError(err, "ExitCode")
				return
			}
		}
		if (zb0001Mask & 0x400) == 0 { // if not omitted
			// write "last_output_at"
			err = en.Append(0xae, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x61, 0x74)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.LastOutputAt)
			if err != nil {
				err = msgp.WrapError(err, "LastOutputAt")
				return
			}
		}
		if (zb0001Mask & 0x800) == 0 { // if not omitted
			// write "last_input_at"
			err = en.Append(0xad, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x61, 0x74)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.LastInputAt)
			if err != nil {
				err = msgp.WrapError(err, "LastInputAt")
				return
			}
		}
		// write "screen"
		err = en.Append(0xa6, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e)
		if err != nil {
			return
		}
		err = en.WriteArrayHeader(uint32(len(z.Screen)))
		if err != nil {
			err = msgp.WrapError(err, "Screen")
			return
		}
		for za0001 := range z.Screen {
			err = en.WriteArrayHeader(uint32(len(z.Screen[za0001])))
			if err != nil {
				err = msgp.WrapError(err, "Screen", za0001)
				return
			}
			for za0002 := range z.Screen[za0001] {
				err = z.Screen[za0001][za0002].EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "Screen", za0001, za0002)
					return
				}
			}
		}
		// write "cursor_row"
		err = en.Append(0xaa, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x5f, 0x72, 0x6f, 0x77)
		if err != nil {
			return
		}
		err = en.WriteInt(z.CursorRow)
		if err != nil {
			err = msgp.WrapError(err, "CursorRow")
			return
		}
		// write "cursor_col"
		err = en.Append(0xaa, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x6c)
		if err != nil {
			return
		}
		err = en.WriteInt(z.CursorCol)
		if err != nil {
			err = msgp.WrapError(err, "CursorCol")
			return
		}
		if (zb0001Mask & 0x8000) == 0 { // if not omitted
			// write "cursor_style"
			err = en.Append(0xac, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x5f, 0x73, 0x74, 0x79, 0x6c, 0x65)
			if err != nil {
				return
			}
			err = en.WriteUint8(z.CursorStyle)
			if err != nil {
				err = msgp.WrapError(err, "CursorStyle")
				return
			}
		}
		if (zb0001Mask & 0x10000) == 0 { // if not omitted
			// write "cursor_blink"
			err = en.Append(0xac, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x5f, 0x62, 0x6c, 0x69, 0x6e, 0x6b)
			if err != nil {
				return
			}
			err = en.WriteBool(z.CursorBlink)
			if err != nil {
				err = msgp.WrapError(err, "CursorBlink")
				return
			}
		}
		if (zb0001Mask & 0x20000) == 0 { // if not omitted
			// write "style_set"
			err = en.Append(0xa9, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x74)
			if err != nil {
				return
			}
			err = en.WriteBool(z.StyleSet)
			if err != nil {
				err = msgp.WrapError(err, "StyleSet")
				return
			}
		}
		if (zb0001Mask & 0x40000) == 0 { // if not omitted
			// write "app_cursor"
			err = en.Append(0xaa, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72)
			if err != nil {
				return
			}
			err = en.WriteBool(z.AppCursor)
			if err != nil {
				err = msgp.WrapError(err, "AppCursor")
				return
			}
		}
		if (zb0001Mask & 0x80000) == 0 { // if not omitted
			// write "mem_scrollback"
			err = en.Append(0xae, 0x6d, 0x65, 0x6d, 0x5f, 0x73, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b)
			if err != nil {
				return
			}
			err = en.WriteArrayHeader(uint32(len(z.MemScrollback)))
			if err != nil {
				err = msgp.WrapError(err, "MemScrollback")
				return
			}
			for za0003 := range z.MemScrollback {
				err = en.WriteArrayHeader(uint32(len(z.MemScrollback[za0003])))
				if err != nil {
					err = msgp.WrapError(err, "MemScrollback", za0003)
					return
				}
				for za0004 := range z.MemScrollback[za0003] {
					err = z.MemScrollback[za0003][za0004].EncodeMsg(en)
					if err != nil {
						err = msgp.WrapError(err, "MemScrollback", za0003, za0004)
						return
					}
				}
			}
		}
		// write "disk_fd"
		err = en.Append(0xa7, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x66, 0x64)
		if err != nil {
			return
		}
		err = en.WriteInt(z.DiskFD)
		if err != nil {
			err = msgp.WrapError(err, "DiskFD")
			return
		}
		if (zb0001Mask & 0x200000) == 0 { // if not omitted
			// write "disk_offsets"
			err = en.Append(0xac, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
			if err != nil {
				return
			}
			err = en.WriteArrayHeader(uint32(len(z.DiskOffsets)))
			if err != nil {
				err = msgp.WrapError(err, "DiskOffsets")
				return
			}
			for za0005 := range z.DiskOffsets {
				err = en.WriteInt64(z.DiskOffsets[za0005])
				if err != nil {
					err = msgp.WrapError(err, "DiskOffsets", za0005)
					return
				}
			}
		}
		if (zb0001Mask & 0x400000) == 0 { // if not omitted
			// write "disk_size"
			err = en.Append(0xa9, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.DiskSize)
			if err != nil {
				err = msgp.WrapError(err, "DiskSize")
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TabState) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(23)
	var zb0001Mask uint32 /* 23 bits */
	_ = zb0001Mask
	if z.Name == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Title == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.CWD == "" {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Exited == false {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.ExitCode == 0 {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.LastOutputAt == 0 {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.LastInputAt == 0 {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	if z.CursorStyle == 0 {
		zb0001Len--
		zb0001Mask |= 0x8000
	}
	if z.CursorBlink == false {
		zb0001Len--
		zb0001Mask |= 0x10000
	}
	if z.StyleSet == false {
		zb0001Len--
		zb0001Mask |= 0x20000
	}
	if z.AppCursor == false {
		zb0001Len--
		zb0001Mask |= 0x40000
	}
	if z.MemScrollback == nil {
		zb0001Len--
		zb0001Mask |= 0x80000
	}
	if z.DiskOffsets == nil {
		zb0001Len--
		zb0001Mask |= 0x200000
	}
	if z.DiskSize == 0 {
		zb0001Len--
		zb0001Mask |= 0x400000
	}
	// variable map header, size zb0001Len
	o = msgp.AppendMapHeader(o, zb0001Len)

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "id"
		o = append(o, 0xa2, 0x69, 0x64)
		o = msgp.AppendUint32(o, z.ID)
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "name"
			o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
			o = msgp.AppendString(o, z.Name)
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "title"
			o = append(o, 0xa5, 0x74, 0x69, 0x74, 0x6c, 0x65)
			o = msgp.AppendString(o, z.Title)
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "cwd"
			o = append(o, 0xa3, 0x63, 0x77, 0x64)
			o = msgp.AppendString(o, z.CWD)
		}
		// string "cols"
		o = append(o, 0xa4, 0x63, 0x6f, 0x6c, 0x73)
		o = msgp.AppendInt(o, z.Cols)
		// string "rows"
		o = append(o, 0xa4, 0x72, 0x6f, 0x77, 0x73)
		o = msgp.AppendInt(o, z.Rows)
		// string "ptmx_fd"
		o = append(o, 0xa7, 0x70, 0x74, 0x6d, 0x78, 0x5f, 0x66, 0x64)
		o = msgp.AppendInt(o, z.PtmxFD)
		// string "child_pid"
		o = append(o, 0xa9, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x5f, 0x70, 0x69, 0x64)
		o = msgp.AppendInt(o, z.ChildPID)
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// string "exited"
			o = append(o, 0xa6, 0x65, 0x78, 0x69, 0x74, 0x65, 0x64)
			o = msgp.AppendBool(o, z.Exited)
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// string "exit_code"
			o = append(o, 0xa9, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65)
			o = msgp.AppendInt(o, z.ExitCode)
		}
		if (zb0001Mask & 0x400) == 0 { // if not omitted
			// string "last_output_at"
			o = append(o, 0xae, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x61, 0x74)
			o = msgp.AppendInt64(o, z.LastOutputAt)
		}
		if (zb0001Mask & 0x800) == 0 { // if not omitted
			// string "last_input_at"
			o = append(o, 0xad, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x61, 0x74)
			o = msgp.AppendInt64(o, z.LastInputAt)
		}
		// string "screen"
		o = append(o, 0xa6, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e)
		o = msgp.AppendArrayHeader(o, uint32(len(z.Screen)))
		for za0001 := range z.Screen {
			o = msgp.AppendArrayHeader(o, uint32(len(z.Screen[za0001])))
			for za0002 := range z.Screen[za0001] {
				o, err = z.Screen[za0001][za0002].MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "Screen", za0001, za0002)
					return
				}
			}
		}
		// string "cursor_row"
		o = append(o, 0xaa, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x5f, 0x72, 0x6f, 0x77)
		o = msgp.AppendInt(o, z.CursorRow)
		// string "cursor_col"
		o = append(o, 0xaa, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x6c)
		o = msgp.AppendInt(o, z.CursorCol)
		if (zb0001Mask & 0x8000) == 0 { // if not omitted
			// string "cursor_style"
			o = append(o, 0xac, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x5f, 0x73, 0x74, 0x79, 0x6c, 0x65)
			o = msgp.AppendUint8(o, z.CursorStyle)
		}
		if (zb0001Mask & 0x10000) == 0 { // if not omitted
			// string "cursor_blink"
			o = append(o, 0xac, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x5f, 0x62, 0x6c, 0x69, 0x6e, 0x6b)
			o = msgp.AppendBool(o, z.CursorBlink)
		}
		if (zb0001Mask & 0x20000) == 0 { // if not omitted
			// string "style_set"
			o = append(o, 0xa9, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x74)
			o = msgp.AppendBool(o, z.StyleSet)
		}
		if (zb0001Mask & 0x40000) == 0 { // if not omitted
			// string "app_cursor"
			o = append(o, 0xaa, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72)
			o = msgp.AppendBool(o, z.AppCursor)
		}
		if (zb0001Mask & 0x80000) == 0 { // if not omitted
			// string "mem_scrollback"
			o = append(o, 0xae, 0x6d, 0x65, 0x6d, 0x5f, 0x73, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b)
			o = msgp.AppendArrayHeader(o, uint32(len(z.MemScrollback)))
			for za0003 := range z.MemScrollback {
				o = msgp.AppendArrayHeader(o, uint32(len(z.MemScrollback[za0003])))
				for za0004 := range z.MemScrollback[za0003] {
					o, err = z.MemScrollback[za0003][za0004].MarshalMsg(o)
					if err != nil {
						err = msgp.WrapError(err, "MemScrollback", za0003, za0004)
						return
					}
				}
			}
		}
		// string "disk_fd"
		o = append(o, 0xa7, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x66, 0x64)
		o = msgp.AppendInt(o, z.DiskFD)
		if (zb0001Mask & 0x200000) == 0 { // if not omitted
			// string "disk_offsets"
			o = append(o, 0xac, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
			o = msgp.AppendArrayHeader(o, uint32(len(z.DiskOffsets)))
			for za0005 := range z.DiskOffsets {
				o = msgp.AppendInt64(o, z.DiskOffsets[za0005])
			}
		}
		if (zb0001Mask & 0x400000) == 0 { // if not omitted
			// string "disk_size"
			o = append(o, 0xa9, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65)
			o = msgp.AppendInt64(o, z.DiskSize)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TabState) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "title":
			z.Title, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "cwd":
			z.CWD, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CWD")
				return
			}
		case "cols":
			z.Cols, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Cols")
				return
			}
		case "rows":
			z.Rows, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Rows")
				return
			}
		case "ptmx_fd":
			z.PtmxFD, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PtmxFD")
				return
			}
		case "child_pid":
			z.ChildPID, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ChildPID")
				return
			}
		case "exited":
			z.Exited, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Exited")
				return
			}
		case "exit_code":
			z.ExitCode, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExitCode")
				return
			}
		case "last_output_at":
			z.LastOutputAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LastOutputAt")
				return
			}
		case "last_input_at":
			z.LastInputAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LastInputAt")
				return
			}
		case "screen":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Screen")
				return
			}
			if cap(z.Screen) >= int(zb0002) {
				z.Screen = (z.Screen)[:zb0002]
			} else {
				z.Screen = make([][]protocol.Cell, zb0002)
			}
			for za0001 := range z.Screen {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Screen", za0001)
					return
				}
				if cap(z.Screen[za0001]) >= int(zb0003) {
					z.Screen[za0001] = (z.Screen[za0001])[:zb0003]
				} else {
					z.Screen[za0001] = make([]protocol.Cell, zb0003)
				}
				for za0002 := range z.Screen[za0001] {
					bts, err = z.Screen[za0001][za0002].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Screen", za0001, za0002)
						return
					}
				}
			}
		case "cursor_row":
			z.CursorRow, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CursorRow")
				return
			}
		case "cursor_col":
			z.CursorCol, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CursorCol")
				return
			}
		case "cursor_style":
			z.CursorStyle, bts, err = msgp.ReadUint8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CursorStyle")
				return
			}
		case "cursor_blink":
			z.CursorBlink, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CursorBlink")
				return
			}
		case "style_set":
			z.StyleSet, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StyleSet")
				return
			}
		case "app_cursor":
			z.AppCursor, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AppCursor")
				return
			}
		case "mem_scrollback":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MemScrollback")
				return
			}
			if cap(z.MemScrollback) >= int(zb0004) {
				z.MemScrollback = (z.MemScrollback)[:zb0004]
			} else {
				z.MemScrollback = make([][]protocol.Cell, zb0004)
			}
			for za0003 := range z.MemScrollback {
				var zb0005 uint32
				zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "MemScrollback", za0003)
					return
				}
				if cap(z.MemScrollback[za0003]) >= int(zb0005) {
					z.MemScrollback[za0003] = (z.MemScrollback[za0003])[:zb0005]
				} else {
					z.MemScrollback[za0003] = make([]protocol.Cell, zb0005)
				}
				for za0004 := range z.MemScrollback[za0003] {
					bts, err = z.MemScrollback[za0003][za0004].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "MemScrollback", za0003, za0004)
						return
					}
				}
			}
		case "disk_fd":
			z.DiskFD, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DiskFD")
				return
			}
		case "disk_offsets":
			var zb0006 uint32
			zb0006, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DiskOffsets")
				return
			}
			if cap(z.DiskOffsets) >= int(zb0006) {
				z.DiskOffsets = (z.DiskOffsets)[:zb0006]
			} else {
				z.DiskOffsets = make([]int64, zb0006)
			}
			for za0005 := range z.DiskOffsets {
				z.DiskOffsets[za0005], bts, err = msgp.ReadInt64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "DiskOffsets", za0005)
					return
				}
			}
		case "disk_size":
			z.DiskSize, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DiskSize")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TabState) Msgsize() (s int) {
	s = 3 + 3 + msgp.Uint32Size + 5 + msgp.StringPrefixSize + len(z.Name) + 6 + msgp.StringPrefixSize + len(z.Title) + 4 + msgp.StringPrefixSize + len(z.CWD) + 5 + msgp.IntSize + 5 + msgp.IntSize + 8 + msgp.IntSize + 10 + msgp.IntSize + 7 + msgp.BoolSize + 10 + msgp.IntSize + 15 + msgp.Int64Size + 14 + msgp.Int64Size + 7 + msgp.ArrayHeaderSize
	for za0001 := range z.Screen {
		s += msgp.ArrayHeaderSize
		for za0002 := range z.Screen[za0001] {
			s += z.Screen[za0001][za0002].Msgsize()
		}
	}
	s += 11 + msgp.IntSize + 11 + msgp.IntSize + 13 + msgp.Uint8Size + 13 + msgp.BoolSize + 10 + msgp.BoolSize + 11 + msgp.BoolSize + 15 + msgp.ArrayHeaderSize
	for za0003 := range z.MemScrollback {
		s += msgp.ArrayHeaderSize
		for za0004 := range z.MemScrollback[za0003] {
			s += z.MemScrollback[za0003][za0004].Msgsize()
		}
	}
	s += 8 + msgp.IntSize + 13 + msgp.ArrayHeaderSize + (len(z.DiskOffsets) * (msgp.Int64Size)) + 10 + msgp.Int64Size
	return
}
