// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package protocol

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Attach) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "session_name":
			z.SessionName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SessionName")
				return
			}
		case "new_if_missing":
			z.NewIfMissing, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "NewIfMissing")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Attach) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "session_name"
	err = en.Append(0x82, 0xac, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.SessionName)
	if err != nil {
		err = msgp.WrapError(err, "SessionName")
		return
	}
	// write "new_if_missing"
	err = en.Append(0xae, 0x6e, 0x65, 0x77, 0x5f, 0x69, 0x66, 0x5f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	err = en.WriteBool(z.NewIfMissing)
	if err != nil {
		err = msgp.WrapError(err, "NewIfMissing")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Attach) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "session_name"
	o = append(o, 0x82, 0xac, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.SessionName)
	// string "new_if_missing"
	o = append(o, 0xae, 0x6e, 0x65, 0x77, 0x5f, 0x69, 0x66, 0x5f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67)
	o = msgp.AppendBool(o, z.NewIfMissing)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Attach) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "session_name":
			z.SessionName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SessionName")
				return
			}
		case "new_if_missing":
			z.NewIfMissing, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NewIfMissing")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Attach) Msgsize() (s int) {
	s = 1 + 13 + msgp.StringPrefixSize + len(z.SessionName) + 15 + msgp.BoolSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Attached) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "session_name":
			z.SessionName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SessionName")
				return
			}
		case "tabs":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Tabs")
				return
			}
			if cap(z.Tabs) >= int(zb0002) {
				z.Tabs = (z.Tabs)[:zb0002]
			} else {
				z.Tabs = make([]TabInfo, zb0002)
			}
			for za0001 := range z.Tabs {
				err = z.Tabs[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Tabs", za0001)
					return
				}
			}
		case "focused_id":
			z.FocusedID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "FocusedID")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Attached) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "session_name"
	err = en.Append(0x83, 0xac, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.SessionName)
	if err != nil {
		err = msgp.WrapError(err, "SessionName")
		return
	}
	// write "tabs"
	err = en.Append(0xa4, 0x74, 0x61, 0x62, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Tabs)))
	if err != nil {
		err = msgp.WrapError(err, "Tabs")
		return
	}
	for za0001 := range z.Tabs {
		err = z.Tabs[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Tabs", za0001)
			return
		}
	}
	// write "focused_id"
	err = en.Append(0xaa, 0x66, 0x6f, 0x63, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.FocusedID)
	if err != nil {
		err = msgp.WrapError(err, "FocusedID")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Attached) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "session_name"
	o = append(o, 0x83, 0xac, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.SessionName)
	// string "tabs"
	o = append(o, 0xa4, 0x74, 0x61, 0x62, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Tabs)))
	for za0001 := range z.Tabs {
		o, err = z.Tabs[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Tabs", za0001)
			return
		}
	}
	// string "focused_id"
	o = append(o, 0xaa, 0x66, 0x6f, 0x63, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.FocusedID)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Attached) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "session_name":
			z.SessionName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SessionName")
				return
			}
		case "tabs":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Tabs")
				return
			}
			if cap(z.Tabs) >= int(zb0002) {
				z.Tabs = (z.Tabs)[:zb0002]
			} else {
				z.Tabs = make([]TabInfo, zb0002)
			}
			for za0001 := range z.Tabs {
				bts, err = z.Tabs[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Tabs", za0001)
					return
				}
			}
		case "focused_id":
			z.FocusedID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FocusedID")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Attached) Msgsize() (s int) {
	s = 1 + 13 + msgp.StringPrefixSize + len(z.SessionName) + 5 + msgp.ArrayHeaderSize
	for za0001 := range z.Tabs {
		s += z.Tabs[za0001].Msgsize()
	}
	s += 11 + msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Bell) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Bell) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "id"
	err = en.Append(0x81, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Bell) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "id"
	o = append(o, 0x81, 0xa2, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.ID)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Bell) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Bell) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Cell) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "c":
			z.Content, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "s":
			z.Style, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "Style")
				return
			}
		case "w":
			z.Width, err = dc.ReadUint8()
			if err != nil {
				err = msgp.WrapError(err, "Width")
				return
			}
		case "fg":
			z.FgRGB, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "FgRGB")
				return
			}
		case "bg":
			z.BgRGB, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "BgRGB")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Cell) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(5)
	var zb0001Mask uint8 /* 5 bits */
	_ = zb0001Mask
	if z.FgRGB == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.BgRGB == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "c"
		err = en.Append(0xa1, 0x63)
		if err != nil {
			return
		}
		err = en.WriteString(z.Content)
		if err != nil {
			err = msgp.WrapError(err, "Content")
			return
		}
		// write "s"
		err = en.Append(0xa1, 0x73)
		if err != nil {
			return
		}
		err = en.WriteUint32(z.Style)
		if err != nil {
			err = msgp.WrapError(err, "Style")
			return
		}
		// write "w"
		err = en.Append(0xa1, 0x77)
		if err != nil {
			return
		}
		err = en.WriteUint8(z.Width)
		if err != nil {
			err = msgp.WrapError(err, "Width")
			return
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "fg"
			err = en.Append(0xa2, 0x66, 0x67)
			if err != nil {
				return
			}
			err = en.WriteUint32(z.FgRGB)
			if err != nil {
				err = msgp.WrapError(err, "FgRGB")
				return
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "bg"
			err = en.Append(0xa2, 0x62, 0x67)
			if err != nil {
				return
			}
			err = en.WriteUint32(z.BgRGB)
			if err != nil {
				err = msgp.WrapError(err, "BgRGB")
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Cell) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(5)
	var zb0001Mask uint8 /* 5 bits */
	_ = zb0001Mask
	if z.FgRGB == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.BgRGB == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "c"
		o = append(o, 0xa1, 0x63)
		o = msgp.AppendString(o, z.Content)
		// string "s"
		o = append(o, 0xa1, 0x73)
		o = msgp.AppendUint32(o, z.Style)
		// string "w"
		o = append(o, 0xa1, 0x77)
		o = msgp.AppendUint8(o, z.Width)
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "fg"
			o = append(o, 0xa2, 0x66, 0x67)
			o = msgp.AppendUint32(o, z.FgRGB)
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "bg"
			o = append(o, 0xa2, 0x62, 0x67)
			o = msgp.AppendUint32(o, z.BgRGB)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Cell) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "c":
			z.Content, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "s":
			z.Style, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Style")
				return
			}
		case "w":
			z.Width, bts, err = msgp.ReadUint8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Width")
				return
			}
		case "fg":
			z.FgRGB, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FgRGB")
				return
			}
		case "bg":
			z.BgRGB, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BgRGB")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Cell) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len(z.Content) + 2 + msgp.Uint32Size + 2 + msgp.Uint8Size + 3 + msgp.Uint32Size + 3 + msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CellDiff) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "cells":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Cells")
				return
			}
			if cap(z.Cells) >= int(zb0002) {
				z.Cells = (z.Cells)[:zb0002]
			} else {
				z.Cells = make([]CellDiffEntry, zb0002)
			}
			for za0001 := range z.Cells {
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Cells", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Cells", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "r":
						z.Cells[za0001].Row, err = dc.ReadUint16()
						if err != nil {
							err = msgp.WrapError(err, "Cells", za0001, "Row")
							return
						}
					case "c":
						z.Cells[za0001].Col, err = dc.ReadUint16()
						if err != nil {
							err = msgp.WrapError(err, "Cells", za0001, "Col")
							return
						}
					case "v":
						err = z.Cells[za0001].Cell.DecodeMsg(dc)
						if err != nil {
							err = msgp.WrapError(err, "Cells", za0001, "Cell")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Cells", za0001)
							return
						}
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CellDiff) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "id"
	err = en.Append(0x82, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "cells"
	err = en.Append(0xa5, 0x63, 0x65, 0x6c, 0x6c, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Cells)))
	if err != nil {
		err = msgp.WrapError(err, "Cells")
		return
	}
	for za0001 := range z.Cells {
		// map header, size 3
		// write "r"
		err = en.Append(0x83, 0xa1, 0x72)
		if err != nil {
			return
		}
		err = en.WriteUint16(z.Cells[za0001].Row)
		if err != nil {
			err = msgp.WrapError(err, "Cells", za0001, "Row")
			return
		}
		// write "c"
		err = en.Append(0xa1, 0x63)
		if err != nil {
			return
		}
		err = en.WriteUint16(z.Cells[za0001].Col)
		if err != nil {
			err = msgp.WrapError(err, "Cells", za0001, "Col")
			return
		}
		// write "v"
		err = en.Append(0xa1, 0x76)
		if err != nil {
			return
		}
		err = z.Cells[za0001].Cell.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Cells", za0001, "Cell")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CellDiff) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "id"
	o = append(o, 0x82, 0xa2, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.ID)
	// string "cells"
	o = append(o, 0xa5, 0x63, 0x65, 0x6c, 0x6c, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Cells)))
	for za0001 := range z.Cells {
		// map header, size 3
		// string "r"
		o = append(o, 0x83, 0xa1, 0x72)
		o = msgp.AppendUint16(o, z.Cells[za0001].Row)
		// string "c"
		o = append(o, 0xa1, 0x63)
		o = msgp.AppendUint16(o, z.Cells[za0001].Col)
		// string "v"
		o = append(o, 0xa1, 0x76)
		o, err = z.Cells[za0001].Cell.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Cells", za0001, "Cell")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CellDiff) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "cells":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Cells")
				return
			}
			if cap(z.Cells) >= int(zb0002) {
				z.Cells = (z.Cells)[:zb0002]
			} else {
				z.Cells = make([]CellDiffEntry, zb0002)
			}
			for za0001 := range z.Cells {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Cells", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Cells", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "r":
						z.Cells[za0001].Row, bts, err = msgp.ReadUint16Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Cells", za0001, "Row")
							return
						}
					case "c":
						z.Cells[za0001].Col, bts, err = msgp.ReadUint16Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Cells", za0001, "Col")
							return
						}
					case "v":
						bts, err = z.Cells[za0001].Cell.UnmarshalMsg(bts)
						if err != nil {
							err = msgp.WrapError(err, "Cells", za0001, "Cell")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Cells", za0001)
							return
						}
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CellDiff) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint32Size + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Cells {
		s += 1 + 2 + msgp.Uint16Size + 2 + msgp.Uint16Size + 2 + z.Cells[za0001].Cell.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CellDiffEntry) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "r":
			z.Row, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Row")
				return
			}
		case "c":
			z.Col, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Col")
				return
			}
		case "v":
			err = z.Cell.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Cell")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CellDiffEntry) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "r"
	err = en.Append(0x83, 0xa1, 0x72)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Row)
	if err != nil {
		err = msgp.WrapError(err, "Row")
		return
	}
	// write "c"
	err = en.Append(0xa1, 0x63)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Col)
	if err != nil {
		err = msgp.WrapError(err, "Col")
		return
	}
	// write "v"
	err = en.Append(0xa1, 0x76)
	if err != nil {
		return
	}
	err = z.Cell.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Cell")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CellDiffEntry) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "r"
	o = append(o, 0x83, 0xa1, 0x72)
	o = msgp.AppendUint16(o, z.Row)
	// string "c"
	o = append(o, 0xa1, 0x63)
	o = msgp.AppendUint16(o, z.Col)
	// string "v"
	o = append(o, 0xa1, 0x76)
	o, err = z.Cell.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Cell")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CellDiffEntry) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "r":
			z.Row, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Row")
				return
			}
		case "c":
			z.Col, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Col")
				return
			}
		case "v":
			bts, err = z.Cell.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Cell")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CellDiffEntry) Msgsize() (s int) {
	s = 1 + 2 + msgp.Uint16Size + 2 + msgp.Uint16Size + 2 + z.Cell.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CellFull) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "cols":
			z.Cols, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Cols")
				return
			}
		case "rows":
			z.Rows, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Rows")
				return
			}
		case "grid":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Grid")
				return
			}
			if cap(z.Grid) >= int(zb0002) {
				z.Grid = (z.Grid)[:zb0002]
			} else {
				z.Grid = make([][]Cell, zb0002)
			}
			for za0001 := range z.Grid {
				var zb0003 uint32
				zb0003, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "Grid", za0001)
					return
				}
				if cap(z.Grid[za0001]) >= int(zb0003) {
					z.Grid[za0001] = (z.Grid[za0001])[:zb0003]
				} else {
					z.Grid[za0001] = make([]Cell, zb0003)
				}
				for za0002 := range z.Grid[za0001] {
					err = z.Grid[za0001][za0002].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Grid", za0001, za0002)
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CellFull) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "id"
	err = en.Append(0x84, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "cols"
	err = en.Append(0xa4, 0x63, 0x6f, 0x6c, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Cols)
	if err != nil {
		err = msgp.WrapError(err, "Cols")
		return
	}
	// write "rows"
	err = en.Append(0xa4, 0x72, 0x6f, 0x77, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Rows)
	if err != nil {
		err = msgp.WrapError(err, "Rows")
		return
	}
	// write "grid"
	err = en.Append(0xa4, 0x67, 0x72, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Grid)))
	if err != nil {
		err = msgp.WrapError(err, "Grid")
		return
	}
	for za0001 := range z.Grid {
		err = en.WriteArrayHeader(uint32(len(z.Grid[za0001])))
		if err != nil {
			err = msgp.WrapError(err, "Grid", za0001)
			return
		}
		for za0002 := range z.Grid[za0001] {
			err = z.Grid[za0001][za0002].EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Grid", za0001, za0002)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CellFull) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "id"
	o = append(o, 0x84, 0xa2, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.ID)
	// string "cols"
	o = append(o, 0xa4, 0x63, 0x6f, 0x6c, 0x73)
	o = msgp.AppendUint16(o, z.Cols)
	// string "rows"
	o = append(o, 0xa4, 0x72, 0x6f, 0x77, 0x73)
	o = msgp.AppendUint16(o, z.Rows)
	// string "grid"
	o = append(o, 0xa4, 0x67, 0x72, 0x69, 0x64)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Grid)))
	for za0001 := range z.Grid {
		o = msgp.AppendArrayHeader(o, uint32(len(z.Grid[za0001])))
		for za0002 := range z.Grid[za0001] {
			o, err = z.Grid[za0001][za0002].MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Grid", za0001, za0002)
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CellFull) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "cols":
			z.Cols, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Cols")
				return
			}
		case "rows":
			z.Rows, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Rows")
				return
			}
		case "grid":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Grid")
				return
			}
			if cap(z.Grid) >= int(zb0002) {
				z.Grid = (z.Grid)[:zb0002]
			} else {
				z.Grid = make([][]Cell, zb0002)
			}
			for za0001 := range z.Grid {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Grid", za0001)
					return
				}
				if cap(z.Grid[za0001]) >= int(zb0003) {
					z.Grid[za0001] = (z.Grid[za0001])[:zb0003]
				} else {
					z.Grid[za0001] = make([]Cell, zb0003)
				}
				for za0002 := range z.Grid[za0001] {
					bts, err = z.Grid[za0001][za0002].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Grid", za0001, za0002)
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CellFull) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint32Size + 5 + msgp.Uint16Size + 5 + msgp.Uint16Size + 5 + msgp.ArrayHeaderSize
	for za0001 := range z.Grid {
		s += msgp.ArrayHeaderSize
		for za0002 := range z.Grid[za0001] {
			s += z.Grid[za0001][za0002].Msgsize()
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ChildExit) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "exit_code":
			z.ExitCode, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ExitCode")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ChildExit) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "id"
	err = en.Append(0x82, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "exit_code"
	err = en.Append(0xa9, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ExitCode)
	if err != nil {
		err = msgp.WrapError(err, "ExitCode")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ChildExit) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "id"
	o = append(o, 0x82, 0xa2, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.ID)
	// string "exit_code"
	o = append(o, 0xa9, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65)
	o = msgp.AppendInt32(o, z.ExitCode)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ChildExit) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "exit_code":
			z.ExitCode, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExitCode")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ChildExit) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint32Size + 10 + msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Cursor) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "row":
			z.Row, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Row")
				return
			}
		case "col":
			z.Col, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Col")
				return
			}
		case "visible":
			z.Visible, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Visible")
				return
			}
		case "style":
			z.Style, err = dc.ReadUint8()
			if err != nil {
				err = msgp.WrapError(err, "Style")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Cursor) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "id"
	err = en.Append(0x85, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "row"
	err = en.Append(0xa3, 0x72, 0x6f, 0x77)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Row)
	if err != nil {
		err = msgp.WrapError(err, "Row")
		return
	}
	// write "col"
	err = en.Append(0xa3, 0x63, 0x6f, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Col)
	if err != nil {
		err = msgp.WrapError(err, "Col")
		return
	}
	// write "visible"
	err = en.Append(0xa7, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Visible)
	if err != nil {
		err = msgp.WrapError(err, "Visible")
		return
	}
	// write "style"
	err = en.Append(0xa5, 0x73, 0x74, 0x79, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint8(z.Style)
	if err != nil {
		err = msgp.WrapError(err, "Style")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Cursor) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "id"
	o = append(o, 0x85, 0xa2, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.ID)
	// string "row"
	o = append(o, 0xa3, 0x72, 0x6f, 0x77)
	o = msgp.AppendUint16(o, z.Row)
	// string "col"
	o = append(o, 0xa3, 0x63, 0x6f, 0x6c)
	o = msgp.AppendUint16(o, z.Col)
	// string "visible"
	o = append(o, 0xa7, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65)
	o = msgp.AppendBool(o, z.Visible)
	// string "style"
	o = append(o, 0xa5, 0x73, 0x74, 0x79, 0x6c, 0x65)
	o = msgp.AppendUint8(o, z.Style)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Cursor) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "row":
			z.Row, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Row")
				return
			}
		case "col":
			z.Col, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Col")
				return
			}
		case "visible":
			z.Visible, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Visible")
				return
			}
		case "style":
			z.Style, bts, err = msgp.ReadUint8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Style")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Cursor) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint32Size + 4 + msgp.Uint16Size + 4 + msgp.Uint16Size + 8 + msgp.BoolSize + 6 + msgp.Uint8Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Detach) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Detach) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 0
	_ = z
	err = en.Append(0x80)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Detach) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 0
	_ = z
	o = append(o, 0x80)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Detach) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Detach) Msgsize() (s int) {
	s = 1
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Error) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "code":
			z.Code, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Code")
				return
			}
		case "message":
			z.Message, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Message")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Error) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "code"
	err = en.Append(0x82, 0xa4, 0x63, 0x6f, 0x64, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Code)
	if err != nil {
		err = msgp.WrapError(err, "Code")
		return
	}
	// write "message"
	err = en.Append(0xa7, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Message)
	if err != nil {
		err = msgp.WrapError(err, "Message")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Error) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "code"
	o = append(o, 0x82, 0xa4, 0x63, 0x6f, 0x64, 0x65)
	o = msgp.AppendUint16(o, z.Code)
	// string "message"
	o = append(o, 0xa7, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65)
	o = msgp.AppendString(o, z.Message)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Error) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "code":
			z.Code, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Code")
				return
			}
		case "message":
			z.Message, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Message")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Error) Msgsize() (s int) {
	s = 1 + 5 + msgp.Uint16Size + 8 + msgp.StringPrefixSize + len(z.Message)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Hello) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "version":
			z.Version, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "client_id":
			z.ClientID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ClientID")
				return
			}
		case "caps":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Caps")
				return
			}
			if cap(z.Caps) >= int(zb0002) {
				z.Caps = (z.Caps)[:zb0002]
			} else {
				z.Caps = make([]string, zb0002)
			}
			for za0001 := range z.Caps {
				z.Caps[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Caps", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Hello) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	if z.Caps == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "version"
		err = en.Append(0xa7, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
		if err != nil {
			return
		}
		err = en.WriteUint16(z.Version)
		if err != nil {
			err = msgp.WrapError(err, "Version")
			return
		}
		// write "client_id"
		err = en.Append(0xa9, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64)
		if err != nil {
			return
		}
		err = en.WriteString(z.ClientID)
		if err != nil {
			err = msgp.WrapError(err, "ClientID")
			return
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "caps"
			err = en.Append(0xa4, 0x63, 0x61, 0x70, 0x73)
			if err != nil {
				return
			}
			err = en.WriteArrayHeader(uint32(len(z.Caps)))
			if err != nil {
				err = msgp.WrapError(err, "Caps")
				return
			}
			for za0001 := range z.Caps {
				err = en.WriteString(z.Caps[za0001])
				if err != nil {
					err = msgp.WrapError(err, "Caps", za0001)
					return
				}
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Hello) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	if z.Caps == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "version"
		o = append(o, 0xa7, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
		o = msgp.AppendUint16(o, z.Version)
		// string "client_id"
		o = append(o, 0xa9, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64)
		o = msgp.AppendString(o, z.ClientID)
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "caps"
			o = append(o, 0xa4, 0x63, 0x61, 0x70, 0x73)
			o = msgp.AppendArrayHeader(o, uint32(len(z.Caps)))
			for za0001 := range z.Caps {
				o = msgp.AppendString(o, z.Caps[za0001])
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Hello) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "version":
			z.Version, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "client_id":
			z.ClientID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ClientID")
				return
			}
		case "caps":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Caps")
				return
			}
			if cap(z.Caps) >= int(zb0002) {
				z.Caps = (z.Caps)[:zb0002]
			} else {
				z.Caps = make([]string, zb0002)
			}
			for za0001 := range z.Caps {
				z.Caps[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Caps", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Hello) Msgsize() (s int) {
	s = 1 + 8 + msgp.Uint16Size + 10 + msgp.StringPrefixSize + len(z.ClientID) + 5 + msgp.ArrayHeaderSize
	for za0001 := range z.Caps {
		s += msgp.StringPrefixSize + len(z.Caps[za0001])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *HelloAck) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "server_version":
			z.ServerVersion, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "ServerVersion")
				return
			}
		case "server_id":
			z.ServerID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ServerID")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z HelloAck) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "server_version"
	err = en.Append(0x82, 0xae, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.ServerVersion)
	if err != nil {
		err = msgp.WrapError(err, "ServerVersion")
		return
	}
	// write "server_id"
	err = en.Append(0xa9, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ServerID)
	if err != nil {
		err = msgp.WrapError(err, "ServerID")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z HelloAck) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "server_version"
	o = append(o, 0x82, 0xae, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendUint16(o, z.ServerVersion)
	// string "server_id"
	o = append(o, 0xa9, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.ServerID)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *HelloAck) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "server_version":
			z.ServerVersion, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ServerVersion")
				return
			}
		case "server_id":
			z.ServerID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ServerID")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z HelloAck) Msgsize() (s int) {
	s = 1 + 15 + msgp.Uint16Size + 10 + msgp.StringPrefixSize + len(z.ServerID)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *InputBytes) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "bytes":
			z.Bytes, err = dc.ReadBytes(z.Bytes)
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *InputBytes) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "id"
	err = en.Append(0x82, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "bytes"
	err = en.Append(0xa5, 0x62, 0x79, 0x74, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Bytes)
	if err != nil {
		err = msgp.WrapError(err, "Bytes")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *InputBytes) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "id"
	o = append(o, 0x82, 0xa2, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.ID)
	// string "bytes"
	o = append(o, 0xa5, 0x62, 0x79, 0x74, 0x65, 0x73)
	o = msgp.AppendBytes(o, z.Bytes)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *InputBytes) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "bytes":
			z.Bytes, bts, err = msgp.ReadBytesBytes(bts, z.Bytes)
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *InputBytes) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint32Size + 6 + msgp.BytesPrefixSize + len(z.Bytes)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *InputPaste) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "bytes":
			z.Bytes, err = dc.ReadBytes(z.Bytes)
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *InputPaste) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "id"
	err = en.Append(0x82, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "bytes"
	err = en.Append(0xa5, 0x62, 0x79, 0x74, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Bytes)
	if err != nil {
		err = msgp.WrapError(err, "Bytes")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *InputPaste) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "id"
	o = append(o, 0x82, 0xa2, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.ID)
	// string "bytes"
	o = append(o, 0xa5, 0x62, 0x79, 0x74, 0x65, 0x73)
	o = msgp.AppendBytes(o, z.Bytes)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *InputPaste) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "bytes":
			z.Bytes, bts, err = msgp.ReadBytesBytes(bts, z.Bytes)
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *InputPaste) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint32Size + 6 + msgp.BytesPrefixSize + len(z.Bytes)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MsgType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 uint8
		zb0001, err = dc.ReadUint8()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = MsgType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z MsgType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteUint8(uint8(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z MsgType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendUint8(o, uint8(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MsgType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 uint8
		zb0001, bts, err = msgp.ReadUint8Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = MsgType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z MsgType) Msgsize() (s int) {
	s = msgp.Uint8Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Resize) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "cols":
			z.Cols, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Cols")
				return
			}
		case "rows":
			z.Rows, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Rows")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Resize) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "id"
	err = en.Append(0x83, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "cols"
	err = en.Append(0xa4, 0x63, 0x6f, 0x6c, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Cols)
	if err != nil {
		err = msgp.WrapError(err, "Cols")
		return
	}
	// write "rows"
	err = en.Append(0xa4, 0x72, 0x6f, 0x77, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Rows)
	if err != nil {
		err = msgp.WrapError(err, "Rows")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Resize) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "id"
	o = append(o, 0x83, 0xa2, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.ID)
	// string "cols"
	o = append(o, 0xa4, 0x63, 0x6f, 0x6c, 0x73)
	o = msgp.AppendUint16(o, z.Cols)
	// string "rows"
	o = append(o, 0xa4, 0x72, 0x6f, 0x77, 0x73)
	o = msgp.AppendUint16(o, z.Rows)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Resize) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "cols":
			z.Cols, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Cols")
				return
			}
		case "rows":
			z.Rows, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Rows")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Resize) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint32Size + 5 + msgp.Uint16Size + 5 + msgp.Uint16Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TabClose) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z TabClose) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "id"
	err = en.Append(0x81, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z TabClose) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "id"
	o = append(o, 0x81, 0xa2, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.ID)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TabClose) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z TabClose) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TabCreate) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "cols":
			z.Cols, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Cols")
				return
			}
		case "rows":
			z.Rows, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Rows")
				return
			}
		case "cwd":
			z.Cwd, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Cwd")
				return
			}
		case "command":
			z.Command, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Command")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TabCreate) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(4)
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	if z.Cwd == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Command == "" {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "cols"
		err = en.Append(0xa4, 0x63, 0x6f, 0x6c, 0x73)
		if err != nil {
			return
		}
		err = en.WriteUint16(z.Cols)
		if err != nil {
			err = msgp.WrapError(err, "Cols")
			return
		}
		// write "rows"
		err = en.Append(0xa4, 0x72, 0x6f, 0x77, 0x73)
		if err != nil {
			return
		}
		err = en.WriteUint16(z.Rows)
		if err != nil {
			err = msgp.WrapError(err, "Rows")
			return
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "cwd"
			err = en.Append(0xa3, 0x63, 0x77, 0x64)
			if err != nil {
				return
			}
			err = en.WriteString(z.Cwd)
			if err != nil {
				err = msgp.WrapError(err, "Cwd")
				return
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "command"
			err = en.Append(0xa7, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64)
			if err != nil {
				return
			}
			err = en.WriteString(z.Command)
			if err != nil {
				err = msgp.WrapError(err, "Command")
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TabCreate) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(4)
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	if z.Cwd == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Command == "" {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "cols"
		o = append(o, 0xa4, 0x63, 0x6f, 0x6c, 0x73)
		o = msgp.AppendUint16(o, z.Cols)
		// string "rows"
		o = append(o, 0xa4, 0x72, 0x6f, 0x77, 0x73)
		o = msgp.AppendUint16(o, z.Rows)
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "cwd"
			o = append(o, 0xa3, 0x63, 0x77, 0x64)
			o = msgp.AppendString(o, z.Cwd)
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "command"
			o = append(o, 0xa7, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64)
			o = msgp.AppendString(o, z.Command)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TabCreate) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "cols":
			z.Cols, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Cols")
				return
			}
		case "rows":
			z.Rows, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Rows")
				return
			}
		case "cwd":
			z.Cwd, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Cwd")
				return
			}
		case "command":
			z.Command, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Command")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TabCreate) Msgsize() (s int) {
	s = 1 + 5 + msgp.Uint16Size + 5 + msgp.Uint16Size + 4 + msgp.StringPrefixSize + len(z.Cwd) + 8 + msgp.StringPrefixSize + len(z.Command)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TabCreated) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "info":
			err = z.Info.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Info")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TabCreated) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "info"
	err = en.Append(0x81, 0xa4, 0x69, 0x6e, 0x66, 0x6f)
	if err != nil {
		return
	}
	err = z.Info.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Info")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TabCreated) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "info"
	o = append(o, 0x81, 0xa4, 0x69, 0x6e, 0x66, 0x6f)
	o, err = z.Info.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Info")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TabCreated) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "info":
			bts, err = z.Info.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Info")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TabCreated) Msgsize() (s int) {
	s = 1 + 5 + z.Info.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TabFocus) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z TabFocus) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "id"
	err = en.Append(0x81, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z TabFocus) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "id"
	o = append(o, 0x81, 0xa2, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.ID)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TabFocus) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z TabFocus) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TabInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "title":
			z.Title, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "cols":
			z.Cols, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Cols")
				return
			}
		case "rows":
			z.Rows, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Rows")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TabInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "id"
	err = en.Append(0x84, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "title"
	err = en.Append(0xa5, 0x74, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Title)
	if err != nil {
		err = msgp.WrapError(err, "Title")
		return
	}
	// write "cols"
	err = en.Append(0xa4, 0x63, 0x6f, 0x6c, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Cols)
	if err != nil {
		err = msgp.WrapError(err, "Cols")
		return
	}
	// write "rows"
	err = en.Append(0xa4, 0x72, 0x6f, 0x77, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Rows)
	if err != nil {
		err = msgp.WrapError(err, "Rows")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TabInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "id"
	o = append(o, 0x84, 0xa2, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.ID)
	// string "title"
	o = append(o, 0xa5, 0x74, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.Title)
	// string "cols"
	o = append(o, 0xa4, 0x63, 0x6f, 0x6c, 0x73)
	o = msgp.AppendUint16(o, z.Cols)
	// string "rows"
	o = append(o, 0xa4, 0x72, 0x6f, 0x77, 0x73)
	o = msgp.AppendUint16(o, z.Rows)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TabInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "title":
			z.Title, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "cols":
			z.Cols, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Cols")
				return
			}
		case "rows":
			z.Rows, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Rows")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TabInfo) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint32Size + 6 + msgp.StringPrefixSize + len(z.Title) + 5 + msgp.Uint16Size + 5 + msgp.Uint16Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Title) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "title":
			z.Title, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Title) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "id"
	err = en.Append(0x82, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "title"
	err = en.Append(0xa5, 0x74, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Title)
	if err != nil {
		err = msgp.WrapError(err, "Title")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Title) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "id"
	o = append(o, 0x82, 0xa2, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.ID)
	// string "title"
	o = append(o, 0xa5, 0x74, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.Title)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Title) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "title":
			z.Title, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Title) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint32Size + 6 + msgp.StringPrefixSize + len(z.Title)
	return
}
